"""Initial migration

Revision ID: bef81e194e19
Revises: 
Create Date: 2025-01-28 22:54:36.203954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef81e194e19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_handicap', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('rounds',
    sa.Column('round_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_played', sa.Date(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('num_players', sa.Integer(), nullable=False),
    sa.Column('has_extra', sa.Boolean(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_table('handicap_match',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_1_id', sa.Integer(), nullable=False),
    sa.Column('player_2_id', sa.Integer(), nullable=False),
    sa.Column('player_1_to_2', sa.Integer(), nullable=True),
    sa.Column('player_2_to_1', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_1_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['player_2_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('front_score', sa.Integer(), nullable=True),
    sa.Column('back_score', sa.Integer(), nullable=True),
    sa.Column('extra_score', sa.Integer(), nullable=True),
    sa.Column('front_putt', sa.Integer(), nullable=True),
    sa.Column('back_putt', sa.Integer(), nullable=True),
    sa.Column('extra_putt', sa.Integer(), nullable=True),
    sa.Column('front_game_pt', sa.Integer(), nullable=True),
    sa.Column('back_game_pt', sa.Integer(), nullable=True),
    sa.Column('extra_game_pt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('handicap_match')
    op.drop_table('rounds')
    op.drop_table('members')
    # ### end Alembic commands ###
