# Streamlit Secrets Configuration

# Admin configuration
admin_password = "admin"

# Supabase configuration
[supabase]
url = "https://sukqpdycjfdkzfuquhsp.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1a3FwZHljamZka3pmdXF1aHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDIxOTMsImV4cCI6MjA1NTk3ODE5M30.lRNYqdPao7Rzg7xe0c8TDaELId2cQlBZKyDbrOISm1w"

